version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports:
      - '443:443'
    volumes:
      - /home/hrothery/Inception/srcs/requirements/tools:/etc/nginx/ssl/
      - wp:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on: 
      - wordpress
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    environment: 
      DB_HOST=${DB_HOST}
      DB_NAME=${DB_NAME}
      DB_USER=${DB_USER}
      DB_PWD=${DB_PWD}
      ROOT_PWD=${ROOT_PWD}
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hrothery/data/mariadb 
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hrothery/data/wordpress
  
networks:
  inception:
    driver: bridge